name: Build and Release the ISO

on:
  workflow_dispatch:

env:
  BUILD_DIR: berserk-build
  ISO_REPO: https://github.com/berserkarch/berserk-vm-xfce.git

jobs:
  push:
    runs-on: ubuntu-latest
    container:
      image: docker.io/berserkarch/berserkarch:base-devel
      options: >-
        --security-opt seccomp=unconfined
        --privileged
        --name berserkarch
        --hostname berserk

    steps:
      - uses: actions/checkout@v4

      - name: Update and Sync System
        run: |
          sudo pacman -Syyu --noconfirm

      - name: Clone and build the repo
        run: |
          mkdir -p /berserk-vm-xfce/out
          echo test > /berserk-vm/xfce/out/test

      - name: Upload to Google Drive
        uses: Wtzd8645/upload-to-google-drive-action@v2
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          src_path: ${{ github.workspace }}/berserk-vm-xfce/out/
          dest_folder: ${{ vars.GOOGLE_DRIVE_FOLDER }}
